version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mutalyzer
      - POSTGRES_DB=mutalyzer
      - POSTGRES_PASSWORD=mutalyzer
    ports:
      - '5432:5432'
    volumes:
      - psql.data:/var/lib/postgresql/data
    networks:
      - back

  cache:
    image: redis:alpine
    networks:
      - back

  api:
    image: eidetiq/docker-mutalyzer
    command: mutalyzer-service-json -H 0.0.0.0 -p 8082
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URI=postgresql://mutalyzer:mutalyzer@db/mutalyzer
      - REDIS_URI=redis://cache
      - CACHE_DIR=/data/cache
    ports:
      - '8082:8082'
    volumes:
      - cache.dir:/data/cache
    networks:
      - back
      - front

  batchproc:
    image: eidetiq/docker-mutalyzer
    command: mutalyzer-batch-processor
    depends_on:
      - api
    environment:
      - DATABASE_URI=postgresql://mutalyzer:mutalyzer@db/mutalyzer
      - REDIS_URI=redis://cache
      - CACHE_DIR=/data/cache
    volumes:
      - cache.dir:/data/cache
    networks:
      - back

  web:
    image: eidetiq/docker-mutalyzer
    command: mutalyzer-website -H 0.0.0.0 -p 8080
    depends_on:
      - api
      - batchproc
    environment:
      - DATABASE_URI=postgresql://mutalyzer:mutalyzer@db/mutalyzer
      - REDIS_URI=redis://cache
      - CACHE_DIR=/data/cache
    ports:
      - '8080:8080'
    volumes:
      - cache.dir:/data/cache
    networks:
      - back
      - front

volumes:
  psql.data:
    driver: local
  cache.dir:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge
